### Test facade-service
POST http://localhost:8080/add_message
Content-Type: application/json

{
  "message": "msg3"
}
###
POST http://localhost:8080/add_message
Content-Type: application/json

{
  "message": 123
}
###
POST http://localhost:8080/add_message
Content-Type: application/json

{
  "message": {
    "test": 123
  }
}
###
POST http://localhost:8080/add_message
Content-Type: application/json

{
  "message": []
}



### Test logging-service
POST http://localhost:8081/logging-svc/api/v1.0/add_message
Content-Type: application/json

{"uuid1":  "msg1"}
###

POST http://localhost:8081/logging-svc/api/v1.0/add_message
Content-Type: application/json

{"uuid2":  "msg2"}
###

POST http://localhost:8081/logging-svc/api/v1.0/add_message
Content-Type: application/json

{"uuid1":  123}
###

GET http://localhost:8081/logging-svc/api/v1.0/get_messages
Accept: text/json



### Test message-service
GET http://localhost:8082/message-svc/api/v1.0/get_messages
Accept: text/json
###

POST http://localhost:8082/message-svc/api/v1.0/post_messages
Content-Type: application/json

"test"
###