# services constants
MESSAGES_SERVICE_ADDR = 'http://localhost:8083/message-svc/api/v1.0'
LOGGING_SERVICE_ADDR_1 = 'http://localhost:8091/logging-svc/api/v1.0'
LOGGING_SERVICE_ADDR_2 = 'http://localhost:8092/logging-svc/api/v1.0'
LOGGING_SERVICE_ADDR_3 = 'http://localhost:8093/logging-svc/api/v1.0'
LOGGING_SERVICE_GET_MSGS_ENTRYPOINT = '/get_messages'
LOGGING_SERVICE_ADD_MSG_ENTRYPOINT = '/add_message'
MESSAGES_SERVICE_GET_MSGS_ENTRYPOINT = '/get_messages'
MESSAGES_SERVICE_ADD_MSG_ENTRYPOINT = '/add_message'
